my_project/about_app/urls.py
from django.urls import path
# from . import views
from .views import about, contacts

urlpatterns = [
    path('', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    # path('gallery/', gallery, name='gallery'),
    ]

# http://127.0.0.1:8000/about
# http://127.0.0.1:8000/about/contacts
# http://127.0.0.1:8000/about/gallery

my_project/basket_app/urls.py
# from django.conf.urls import url
# from django.conf.urls import url
from django.urls import path, re_path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "basket"

urlpatterns = [
    # path('', views.basket_detail, name='basket_detail'),
    # path('add/<int:product_id>', views.basket_add, name='basket_add'),
    # path('remove/<int:product_id>', views.basket_remove, name='basket_remove'),
    re_path(r'^$', views.basket_detail, name='basket_detail'),
    re_path(r'^add/(?P<product_id>\d+)/?$', views.basket_add, name='basket_add'),
    re_path(r'^remove/(?P<product_id>\d+)/?$', views.basket_remove, name='basket_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/users_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView
# from my_project import settings
# from django.contrib.auth import views as auth_views
 
app_name = "users"

urlpatterns = [
    # path('login/', views.login_user, name='login'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    # path('logout/', LogoutView.as_view(next_page=settings.LOGOUT_REDIRECT_URL), name='logout'),
    # path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    # path('logout/', LogoutView.as_view(), name='logout'),
]

# http://127.0.0.1:8000
# http://127.0.0.1:8000/users/login
# http://127.0.0.1:8000/users/logout

my_project/templates/base.html
{% load static %}
{% load catalog_tags %}
{% load basket_tags %}
{% load header_tags %}

<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Сайт дипломного проекта{% endblock %}</title>

    <!-- <link type="text/css" href="{% static 'catalog_app/css/jquery-ui.min.css' %}" rel="stylesheet" /> -->
    <link type="text/css" href="{% static 'catalog_app/css/bootstrap.min.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link type="text/css" href="{% static 'catalog_app/css/bootstrap.css' %}" rel="stylesheet" />
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->


    <!-- <link type="text/css" href="{% static 'catalog_app/css/validationEngine.jquery.css' %}" rel="stylesheet" /> -->
    <!-- <link type="text/css" href="{% static 'catalog_app/css/lightslider.min.css' %}" rel="stylesheet" /> -->


    <link type="text/css" href="{% static 'catalog_app/css/styles.css' %}" rel="stylesheet" />

    <link type="text/css" href="{% static 'catalog_app/css/products.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'catalog_app/css/product-container.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'catalog_app/css/products-container.css' %}" rel="stylesheet" />
    <link type="text/css" href="{% static 'catalog_app/css/pagination.css' %}" rel="stylesheet" />

</head>
<body>
    
    {% block mainmenu %}
        <div class="header">
            <ul id="mainmenu" class="mainmenu">
                <li class="logo"><a href="{% url 'index' %}"><div class="logo"></div></a></li>
                    {% get_menu as menu %}
                    {% for m in menu %}
                        <li><a href="{% url m.url_name %}">{{m.title}}</a></li>
                    {% endfor %}
                    <li class="cart">
                        <!-- <div> -->
                            {% with total_items=basket|length %}
                                {% if basket|length > 0 %}
                                    Ваша корзина:
                                    <a href="{% url 'basket:basket_detail' %}">
                                        {{ total_items }} товар{{ total_items|pluralize }},
                                        {{ basket.get_total_price }} Руб</a>
                                {% else %}
                                    Ваша корзина пуста.
                                {% endif %}
                            {% endwith %}
                        <!-- </div> -->
                    </li>

                    <li></li>

                    {% if user.is_authenticated %}
                        <li class="last"> {{user.username}} | <a href="{% url 'users:logout' %}">Выйти</a></li>
                    {% else %}
                        <li class="last"><a href="{% url 'users:login' %}">Войти</a> | <a href="{% url 'users:register' %}#">Регистрация</a></li>
                    {% endif %}
            </ul>
            <div class="clear"></div>
        </div>
    {% endblock mainmenu %}

    {% block content %}
        <p>Скоро тут появится текст...</p>
    {% endblock %}
</body>
</html>