my_project/about_app/urls.py
from django.urls import path
# from . import views
from .views import about, contacts

urlpatterns = [
    path('', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    # path('gallery/', gallery, name='gallery'),
    ]

# http://127.0.0.1:8000/about
# http://127.0.0.1:8000/about/contacts
# http://127.0.0.1:8000/about/gallery

my_project/basket_app/urls.py
# from django.conf.urls import url
# from django.conf.urls import url
from django.urls import path, re_path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "basket"

urlpatterns = [
    # path('', views.basket_detail, name='basket_detail'),
    # path('add/<int:product_id>', views.basket_add, name='basket_add'),
    # path('remove/<int:product_id>', views.basket_remove, name='basket_remove'),
    re_path(r'^$', views.basket_detail, name='basket_detail'),
    re_path(r'^add/(?P<product_id>\d+)/?$', views.basket_add, name='basket_add'),
    re_path(r'^remove/(?P<product_id>\d+)/?$', views.basket_remove, name='basket_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/catalog_app/urls.py
from django.urls import path, re_path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "catalog"

urlpatterns = [
    path('', views.catalog, name='catalog'),
    # path('', views.products, name='index'),
    # path('<slug:cat_slug>/', views.products, name='products'),
    path('products/<slug:cat_slug>/', views.products, name='products'),
    # path('category/<int:cat_id>/', views.show_category, name='category'),
    # path('category/<slug:cat_slug>/', views.show_category, name='category'),
    # path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
    ]

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# http://127.0.0.1:8000/catalog

my_project/catalog_app/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})
        # return reverse('category:show_category', args=[self.slug])
    
    def __str__(self):
        return self.name
                        

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete  = models.CASCADE, related_name='products')
    # category = models.ForeignKey('Category', on_delete  = models.PROTECT, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    # slug = models.SlugField(max_length=200, db_index=True, unique=True)
    image = models.ImageField(upload_to='images/', 
                            default='pngtree-super-selling-product-tag-png-image_4477856.png', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        # return reverse('???', kwargs={'cat_slug': self.slug})
        return reverse('catalog:product_detail', args=[self.id, self.slug])

    def __str__(self):
        return self.name
       

my_project/catalog_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Product, Category
from basket_app.forms import BasketAddProductForm
from django.core.paginator import Paginator
# from django.urls import reverse


# def catalog(request):
#     """Выводит все товары"""
#     # html = """
#     # <h1>Страница каталога.</h1>
#     # <p>Это страница каталога проекта.</p>
#     # """
#     # logger.info("The catalog page has been uploaded.")
#     products = Product.objects.all()
    
#     data = {
#         # 'title': f'Рубрика: {category.name}',
#         # 'title': f'{category.name}',
#         # 'menu': menu,
#         'products': products,
#         # 'basket_product_form': basket_product_form,
#         # 'cat_selected': category.pk,
#     }
#     return render(request, 'catalog_app/catalog.html', context=data)
#     # return HttpResponse(html)

# def catalog(request):
#     """Выводит все товары"""
#     products = Product.objects.all()
#     paginator = Paginator(products, 12)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     # data = {'products': products,}
#     # return render(request, 'catalog_app/catalog.html', context=data)
#     return render(request, 'catalog_app/catalog.html', {'page_obj': page_obj})


# def show_category(request, cat_slug):
#     """Выводит товары выбранной категории"""
#     category = get_object_or_404(Category, slug=cat_slug)
#     products = Product.objects.filter(category_id=category.pk)
#     paginator = Paginator(products, 12)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     data = {'title': f'{category.name}',
#         # 'products': products,
#         'page_obj': page_obj,
#         'cat_selected': category.pk,}
#     return render(request, 'catalog_app/catalog.html', context=data)


def catalog(request):
    return HttpResponseRedirect('/catalog/products/all')

def products(request, cat_slug=None):
    """Выводит товары"""
    if cat_slug == "all":
        products = Product.objects.all()
        title = "all"
        cat_selected = None
    else:
        category = get_object_or_404(Category, slug=cat_slug)
        products = Product.objects.filter(category_id=category.pk)
        title = category.name
        cat_selected = category.pk

    page_number = request.GET.get('page', 1)
    order_by = request.GET.get('order_by', None)

    if order_by and order_by != "default":
        products = products.order_by(order_by)

    paginator = Paginator(products, 12)
    page_obj = paginator.get_page(page_number)
    data = {'title': title,
            'page_obj': page_obj,
            'cat_selected': cat_selected,
            }

    return render(request, 'catalog_app/catalog.html', context=data)


def product_detail(request, id, slug):
    """Выводит выбранный товар"""
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    category_name = product.category.name
    basket_product_form = BasketAddProductForm()
    return render(request, 'catalog_app/product_detail.html',
                  {'product': product, 
                   'category_name': category_name,
                   'basket_product_form': basket_product_form})

my_project/catalog_app/templates/catalog_app/catalog.html
{% extends 'base.html' %}
{% load catalog_tags %}
{% load basket_tags %}

{% block title %}Каталог{% endblock %}

{% block content %}
    <h1>Каталог товаров</h1>

    <div class="container">
        <!-- Список категорий -->
        {% if cat_selected == 0 or cat_selected is None %}
            <li>Все категории</li>
        {% else %}
            <li><a href="{% url 'catalog:catalog' %}">Все категории</a></li>
        {% endif %}

        {% show_categories cat_selected %}

        <!-- Форма фильтров -->
        <form action="{{ request.get_full_path }}" method="get">
            <p class="text-white mx-3 mt-3">Сортировать:</p>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked>
                <label class="form-check-label" for="flexRadioDefault1">
                    По умолчанию
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                <label class="form-check-label" for="flexRadioDefault2">
                    От дешевых к дорогим
                </label>
            </div>
            <div class="form-check text-white mx-3">
                <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                <label class="form-check-label" for="flexRadioDefault3">
                    От дорогих к дешевым
                </label>
            </div>
            <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
        </form>
        <!-- Список товаров -->
        <div id="productsList" class="margin-botton-50">
            <div class="row">
                <div class="col-md-9">
                    {% for product in page_obj %}
                        <div class="products">
                            <div class="prod ">
                                <div class="photo">
                                    <img src="{{ product.image.url }}" height="220" width="220" alt="фото"/>
                                </div>
                                <a class="link" href="{% url 'catalog:product_detail' product.id product.slug %}">{{ product.name }}</a><br>
                                <div class="products-item-price">
                                    <span class="products-item-price__value">{{ product.price }} ₽</span>
                                </div>
                                <!-- <div class="art">Арт. {# { product.id }}</div> -->
                            </div>
                        </div>
                    {% endfor %}
                    
                </div>
            </div>
        </div>
        <!-- Пагинатор -->
        <div>
            {% include 'catalog_app/includes/pagination.html' %}  
        </div>
    </div>
{% endblock %}

my_project/catalog_app/templates/catalog_app/list_categories.html
{% for cat in categories %}
    {% if cat.id == cat_selected %}
        <li class="selected">{{cat.name}}</li>
    {% else %}
        <li><a href="{% url 'catalog:products' cat.slug %}">{{cat.name}}</a></li>
    {% endif %}  
{% endfor %}

my_project/catalog_app/templates/catalog_app/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ category_name }}{% endblock %}

{% block content %}
    <div class="category-name">
        <h3>{{ category_name }}</h3>
    </div>

    <div itemscope itemtype="http://schema.org/Product">
        <div class="container">

            <div class="product-container">
                <div class="product-6rc">

                                <div class="product-image">
                                    {% if product.image %}
                                        <p><img src="{{ product.image.url }}" height="200" alt="{{ product.name }}"></p>
                                    {% endif %}
                                </div>
                            
                    <div class="product-header">
                        <h1 itemprop="name">{{ product.name }}</h1>
                        <div class="product-art">Артикул: {{ product.id }}</div>
                    </div>

                    <div class="product-container">
                        <div class="product-61c">
                            <div class="product-description" itemprop="description">
                                {{ product.description }}
                            </div>
                        <div class="product-4rc">
                            <div class="product-sale-container">
                                <div class="price" itemprop="offers" itemscope itemtype="http://schema.org/Offer">
                                    <div class="product-price">
                                        <span class="product-price__value">{{ product.price }} ₽</span>
                                    </div>
                                </div>
                            </div>
                            <div class="product-buy">
                                <form action="{% url 'basket:basket_add' product.id %}" method="post">
                                    {{ basket_product_form }}
                                    {% csrf_token %}
                                    <input type="submit" value="В корзину">
                                </form>
                            </div>
                            <div class="product-status">
                                <div class="product-status__available">
                                    <i class="fa fa-circle" aria-hidden="{{ product.available }}"></i> 
                                    Есть в наличии
                                </div> 
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>        
{% endblock %}