my_project/about_app/urls.py
from django.urls import path
# from . import views
from .views import about, contacts

urlpatterns = [
    path('', about, name='about'),
    path('contacts/', contacts, name='contacts'),
    # path('gallery/', gallery, name='gallery'),
    ]

# http://127.0.0.1:8000/about
# http://127.0.0.1:8000/about/contacts
# http://127.0.0.1:8000/about/gallery

my_project/basket_app/urls.py
# from django.conf.urls import url
# from django.conf.urls import url
from django.urls import path, re_path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "basket"

urlpatterns = [
    # path('', views.basket_detail, name='basket_detail'),
    # path('add/<int:product_id>', views.basket_add, name='basket_add'),
    # path('remove/<int:product_id>', views.basket_remove, name='basket_remove'),
    re_path(r'^$', views.basket_detail, name='basket_detail'),
    re_path(r'^add/(?P<product_id>\d+)/?$', views.basket_add, name='basket_add'),
    re_path(r'^remove/(?P<product_id>\d+)/?$', views.basket_remove, name='basket_remove'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_project/catalog_app/urls.py
from django.urls import path, re_path
from . import views

from django.conf.urls.static import static
from django.conf import settings

app_name = "catalog"

urlpatterns = [
    path('', views.catalog, name='catalog'),
    # path('', views.products, name='index'),
    # path('<slug:cat_slug>/', views.products, name='products'),
    path('products/<slug:cat_slug>/', views.products, name='products'),
    # path('category/<int:cat_id>/', views.show_category, name='category'),
    # path('category/<slug:cat_slug>/', views.show_category, name='category'),
    # path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    re_path(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail, name='product_detail'),
    ]

# включаем возможность обработки картинок
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# http://127.0.0.1:8000/catalog

my_project/orders_app/urls.py
from django.urls import path, re_path
from . import views
# from orders_app.views import order_create

app_name = "orders"

urlpatterns = [
    re_path(r'^create/$', views.order_create, name='order_create'),
    # path('create/', views.order_create, name='order_create'),
]

my_project/basket_app/models.py
from django.db import models

# Create your models here.

my_project/basket_app/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class BasketAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    

my_project/basket_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog_app.models import Product
from .basket import Basket
from .forms import BasketAddProductForm
from django.contrib.auth.decorators import login_required


@require_POST
def basket_add(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    form = BasketAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('basket:basket_detail')


def basket_remove(request, product_id):
    basket = Basket(request)
    product = get_object_or_404(Product, id=product_id)
    basket.remove(product)
    return redirect('basket:basket_detail')


@login_required(login_url='/users/login/')
def basket_detail(request):
    basket = Basket(request)
    return render(request, 'basket_app/basket.html', {'basket': basket})

my_project/basket_app/templates/basket_app/basket.html
{% extends "base.html" %}
{% load static %}

{% block title %}Ваша корзина{% endblock %}

{% block content %}
    <h1>Ваша корзина</h1>
    <table class="basket">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in basket %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            {% if product.image %}
                            <p><img src="{{ product.image.url }}" alt="My image"></p>
                            {% else %}
                                <img src="{% static 'catalog_app/images/pngtree-super-selling-product-tag-png-image_4477856.png' %}">
                            {% endif %}"     
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'basket:basket_remove' product.id%}">Удалить</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Всего</td>
            <td colspan="4"></td>
            <td class="num">{{ basket.get_total_price }} ₽</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'catalog:catalog' %}" class="button light">Продолжить покупки</a>
        <a href="{% url 'orders:order_create' %}" class="button">Проверить заказ</a>
    </p>
{% endblock %}